export const base44 = {
    entities: {
        ItemAta: {
            list: async (order = '-created_date', limit = 200) => {
                return [
                {
                                "id": "item-1",
                                "nome": "SHURE Sistema sem fio duplo Shure SLxd24d/SM58",
                                "item": "SHURE Sistema sem fio duplo Shure SLxd24d/SM58",
                                "descricao": "Edital: 900142025 | UASG: 930972 | Item: 101",
                                "quantidade": 5,
                                "quantidade_registrada": 5,
                                "valor_unitario": 14100.0,
                                "marca_nome": "SHURE",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/shure-sistema.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-2",
                                "nome": "SHURE Sistema sem fio duplo Shure SLxd24d/SM58",
                                "item": "SHURE Sistema sem fio duplo Shure SLxd24d/SM58",
                                "descricao": "Edital: 900142025 | UASG: 930972 | Item: 102",
                                "quantidade": 1,
                                "quantidade_registrada": 1,
                                "valor_unitario": 14100.0,
                                "marca_nome": "SHURE",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/930972_900142025_102_1.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-3",
                                "nome": "SUMAY SLIM BOX 60W",
                                "item": "SUMAY SLIM BOX 60W",
                                "descricao": "Edital: 900572025 | UASG: 989983 | Item: 6",
                                "quantidade": 2,
                                "quantidade_registrada": 2,
                                "valor_unitario": 190.46,
                                "marca_nome": "SUMAY",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/989983_900572025_6.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-4",
                                "nome": "SUMAY STONE 12 550W",
                                "item": "SUMAY STONE 12 550W",
                                "descricao": "Edital: 901292025 | UASG: 987427 | Item: 3",
                                "quantidade": 8,
                                "quantidade_registrada": 8,
                                "valor_unitario": 835.0,
                                "marca_nome": "SUMAY",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/987427_901292025_3.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-5",
                                "nome": "Soundvoice INTERFACE DE ÁUDIO SOUNDVOICE DELPHI-02",
                                "item": "Soundvoice INTERFACE DE ÁUDIO SOUNDVOICE DELPHI-02",
                                "descricao": "Edital: 900142025 | UASG: 928684 | Item: 3",
                                "quantidade": 1,
                                "quantidade_registrada": 1,
                                "valor_unitario": 538.5,
                                "marca_nome": "Soundvoice",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/928684_900142025_3_1.png",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-6",
                                "nome": "SMART TRIPÉ PARA CELULAR UNIVERSAL COM REGULAGEM SMART SM-300",
                                "item": "SMART TRIPÉ PARA CELULAR UNIVERSAL COM REGULAGEM SMART SM-300",
                                "descricao": "Edital: 900892025 | UASG: 158720 | Item: 53",
                                "quantidade": 4,
                                "quantidade_registrada": 4,
                                "valor_unitario": 375.0,
                                "marca_nome": "SMART",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/158720_900892025_53.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-7",
                                "nome": "THOMASTIK PETER INFELD JOGO DE CORDAS VIOLA 4/4 - ALPHAYUE",
                                "item": "THOMASTIK PETER INFELD JOGO DE CORDAS VIOLA 4/4 - ALPHAYUE",
                                "descricao": "Edital: 900922025 | UASG: 120625 | Item: 13",
                                "quantidade": 45,
                                "quantidade_registrada": 45,
                                "valor_unitario": 550.0,
                                "marca_nome": "THOMASTIK PETER INFELD",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/120625_900922025_13.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-8",
                                "nome": "VANDOREN Palheta de clarineta, nº 3,5, tipo v12,",
                                "item": "VANDOREN Palheta de clarineta, nº 3,5, tipo v12,",
                                "descricao": "Edital: 4642025 | UASG: 120016 | Item: 2",
                                "quantidade": 20,
                                "quantidade_registrada": 20,
                                "valor_unitario": 348.0,
                                "marca_nome": "VANDOREN",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/120016_4642025_2.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-9",
                                "nome": "VANDOREN BOQUILHA BLACK DIAMOND",
                                "item": "VANDOREN BOQUILHA BLACK DIAMOND",
                                "descricao": "Edital: 4642025 | UASG: 120016 | Item: 23",
                                "quantidade": 2,
                                "quantidade_registrada": 2,
                                "valor_unitario": 1489.0,
                                "marca_nome": "VANDOREN",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/120016_4642025_23.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-10",
                                "nome": "LIVERPOOL MACETA DE BUMBO PELUCIA",
                                "item": "LIVERPOOL MACETA DE BUMBO PELUCIA",
                                "descricao": "Edital: 4642025 | UASG: 120016 | Item: 19",
                                "quantidade": 15,
                                "quantidade_registrada": 15,
                                "valor_unitario": 32.0,
                                "marca_nome": "LIVERPOOL",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/120016_4642025_19.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-11",
                                "nome": "LIVERPOOL PAR DE BAQUETAS 7A HCKT",
                                "item": "LIVERPOOL PAR DE BAQUETAS 7A HCKT",
                                "descricao": "Edital: 4642025 | UASG: 120016 | Item: 17",
                                "quantidade": 15,
                                "quantidade_registrada": 15,
                                "valor_unitario": 99.0,
                                "marca_nome": "LIVERPOOL",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/120016_4642025_17.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-12",
                                "nome": "SATY Pedestal para Microfone Saty SMG-10",
                                "item": "SATY Pedestal para Microfone Saty SMG-10",
                                "descricao": "Edital: 903012025 | UASG: 154039 | Item: 38",
                                "quantidade": 5,
                                "quantidade_registrada": 5,
                                "valor_unitario": 109.0,
                                "marca_nome": "SATY",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/154039_903012025_38.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-13",
                                "nome": "LUEN CAIXA DE GUERRA 15X14",
                                "item": "LUEN CAIXA DE GUERRA 15X14",
                                "descricao": "Edital: 900102024 | UASG: 160402 | Item: 55",
                                "quantidade": 12,
                                "quantidade_registrada": 12,
                                "valor_unitario": 223.0,
                                "marca_nome": "LUEN",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/160402_900102024_55.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-14",
                                "nome": "LUEN BOMBO 30X22 Alumisteel Chapa preto 8 Leitosa",
                                "item": "LUEN BOMBO 30X22 Alumisteel Chapa preto 8 Leitosa",
                                "descricao": "Edital: 900102024 | UASG: 160402 | Item: 56",
                                "quantidade": 12,
                                "quantidade_registrada": 12,
                                "valor_unitario": 481.0,
                                "marca_nome": "LUEN",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/160402_900102024_56.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-15",
                                "nome": "SUMAY LIGHT BOX 800W",
                                "item": "SUMAY LIGHT BOX 800W",
                                "descricao": "Edital: 900282025 | UASG: 985825 | Item: 19",
                                "quantidade": 2,
                                "quantidade_registrada": 2,
                                "valor_unitario": 803.85,
                                "marca_nome": "SUMAY",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/985825_900282025_19.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-16",
                                "nome": "LUEN PELE LEITOSA 22",
                                "item": "LUEN PELE LEITOSA 22",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 10",
                                "quantidade": 50,
                                "quantidade_registrada": 50,
                                "valor_unitario": 250.0,
                                "marca_nome": "LUEN",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/731050_900162025_10.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-17",
                                "nome": "CASE CASE",
                                "item": "CASE CASE",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 13",
                                "quantidade": 5,
                                "quantidade_registrada": 5,
                                "valor_unitario": 399.0,
                                "marca_nome": "CASE",
                                "status": "disponivel",
                                "imagem_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-18",
                                "nome": "REMO PELE POROSA14\"",
                                "item": "REMO PELE POROSA14\"",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 15",
                                "quantidade": 30,
                                "quantidade_registrada": 30,
                                "valor_unitario": 250.0,
                                "marca_nome": "REMO",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/731050_900162025_15.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-19",
                                "nome": "LUEN BAQUETA REPIQUE SIMPLES PAR",
                                "item": "LUEN BAQUETA REPIQUE SIMPLES PAR",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 16",
                                "quantidade": 30,
                                "quantidade_registrada": 30,
                                "valor_unitario": 280.0,
                                "marca_nome": "LUEN",
                                "status": "disponivel",
                                "imagem_url": "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-20",
                                "nome": "LUEN BAQUETA VANGUARDA PONTA OLIVIA 409MM PAR",
                                "item": "LUEN BAQUETA VANGUARDA PONTA OLIVIA 409MM PAR",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 18",
                                "quantidade": 30,
                                "quantidade_registrada": 30,
                                "valor_unitario": 24.48,
                                "marca_nome": "LUEN",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/731050_900162025_18.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-21",
                                "nome": "VANDOREN Palheta Sax Tenor nº3 caixa com 5 un",
                                "item": "VANDOREN Palheta Sax Tenor nº3 caixa com 5 un",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 22",
                                "quantidade": 80,
                                "quantidade_registrada": 80,
                                "valor_unitario": 290.54,
                                "marca_nome": "VANDOREN",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/731050_900162025_22.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-22",
                                "nome": "Yamaha Óleo Lubrificante Yamaha Valve Oil - LIGHT 60ml",
                                "item": "Yamaha Óleo Lubrificante Yamaha Valve Oil - LIGHT 60ml",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 29",
                                "quantidade": 70,
                                "quantidade_registrada": 70,
                                "valor_unitario": 135.03,
                                "marca_nome": "Yamaha",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/731050_900162025_29.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-23",
                                "nome": "LUEN Pele 16\"",
                                "item": "LUEN Pele 16\"",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 34",
                                "quantidade": 100,
                                "quantidade_registrada": 100,
                                "valor_unitario": 350.0,
                                "marca_nome": "LUEN",
                                "status": "disponivel",
                                "imagem_url": "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-24",
                                "nome": "LUEN Pele 16\"",
                                "item": "LUEN Pele 16\"",
                                "descricao": "Edital: 900162025 | UASG: 731050 | Item: 35",
                                "quantidade": 60,
                                "quantidade_registrada": 60,
                                "valor_unitario": 400.0,
                                "marca_nome": "LUEN",
                                "status": "disponivel",
                                "imagem_url": "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-25",
                                "nome": "SATY MODELO - SCT 04 Suporte tripé caixa som com ajustes altura",
                                "item": "SATY MODELO - SCT 04 Suporte tripé caixa som com ajustes altura",
                                "descricao": "Edital: 900082025 | UASG: 160237 | Item: 14",
                                "quantidade": 4,
                                "quantidade_registrada": 4,
                                "valor_unitario": 133.03,
                                "marca_nome": "SATY",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/160237_900082025_14.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-26",
                                "nome": "MICHAEL VIOLÃO ELÉTRICO FOLK VMF400 VMF400",
                                "item": "MICHAEL VIOLÃO ELÉTRICO FOLK VMF400 VMF400",
                                "descricao": "Edital: 900542025 | UASG: 988157 | Item: 3",
                                "quantidade": 3,
                                "quantidade_registrada": 3,
                                "valor_unitario": 1401.0,
                                "marca_nome": "MICHAEL",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/988157_900542025_3.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-27",
                                "nome": "MICHAEL VIOLÃO ELÉTRICO CLÁSSICO SEMIFLAT VMS314",
                                "item": "MICHAEL VIOLÃO ELÉTRICO CLÁSSICO SEMIFLAT VMS314",
                                "descricao": "Edital: 900542025 | UASG: 988157 | Item: 4",
                                "quantidade": 3,
                                "quantidade_registrada": 3,
                                "valor_unitario": 864.0,
                                "marca_nome": "MICHAEL",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/988157_900542025_4.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-28",
                                "nome": "VANRAL PELE CLEAR DHC 14\"",
                                "item": "VANRAL PELE CLEAR DHC 14\"",
                                "descricao": "Edital: 900542025 | UASG: 988881 | Item: 1",
                                "quantidade": 20,
                                "quantidade_registrada": 20,
                                "valor_unitario": 40.0,
                                "marca_nome": "VANRAL",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/988881_900542025_1.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-29",
                                "nome": "LIVERPOOL MAÇANETA MC 48",
                                "item": "LIVERPOOL MAÇANETA MC 48",
                                "descricao": "Edital: 900542025 | UASG: 988881 | Item: 5",
                                "quantidade": 7,
                                "quantidade_registrada": 7,
                                "valor_unitario": 17.65,
                                "marca_nome": "LIVERPOOL",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/988881_900542025_5.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-30",
                                "nome": "Nucleo Musical MICROFONE CSMS 58-BK",
                                "item": "Nucleo Musical MICROFONE CSMS 58-BK",
                                "descricao": "Edital: 900402025 | UASG: 984165 | Item: 37",
                                "quantidade": 10,
                                "quantidade_registrada": 10,
                                "valor_unitario": 91.64,
                                "marca_nome": "Nucleo Musical",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/984165_900402025_37.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-31",
                                "nome": "Nucleo Musical Microfone CW 70-BK",
                                "item": "Nucleo Musical Microfone CW 70-BK",
                                "descricao": "Edital: 900402025 | UASG: 984165 | Item: 38",
                                "quantidade": 2,
                                "quantidade_registrada": 2,
                                "valor_unitario": 250.56,
                                "marca_nome": "Nucleo Musical",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/984165_900402025_38.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-32",
                                "nome": "YAMAHA  Violão Acustico NTX1",
                                "item": "YAMAHA  Violão Acustico NTX1",
                                "descricao": "Edital: 901072025 | UASG: 158132 | Item: 5",
                                "quantidade": 54,
                                "quantidade_registrada": 54,
                                "valor_unitario": 3012.99,
                                "marca_nome": "YAMAHA",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/158132_901072025_5.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-33",
                                "nome": "AVS BAG VIOLÃO",
                                "item": "AVS BAG VIOLÃO",
                                "descricao": "Edital: 901072025 | UASG: 158132 | Item: 6",
                                "quantidade": 54,
                                "quantidade_registrada": 54,
                                "valor_unitario": 107.0,
                                "marca_nome": "AVS",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/158132_901072025_6.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-34",
                                "nome": "LUEN Kit de fanfarra alum. 28 instr",
                                "item": "LUEN Kit de fanfarra alum. 28 instr",
                                "descricao": "Edital: 901072025 | UASG: 158132 | Item: 34",
                                "quantidade": 6,
                                "quantidade_registrada": 6,
                                "valor_unitario": 14100.0,
                                "marca_nome": "LUEN",
                                "status": "disponivel",
                                "imagem_url": "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-35",
                                "nome": "BOYA Sistema de Microfone Lapela Boya By-v20 de Lapela",
                                "item": "BOYA Sistema de Microfone Lapela Boya By-v20 de Lapela",
                                "descricao": "Edital: 900312025 | UASG: 987833 | Item: 99",
                                "quantidade": 3,
                                "quantidade_registrada": 3,
                                "valor_unitario": 446.25,
                                "marca_nome": "BOYA",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/987833_900312025_99.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "item-36",
                                "nome": "SUMAY CAIXA DE SOM COMPUTADOR SM-CSPC1310CAIXASOM2.0",
                                "item": "SUMAY CAIXA DE SOM COMPUTADOR SM-CSPC1310CAIXASOM2.0",
                                "descricao": "Edital: 900052025 | UASG: 160422 | Item: 57",
                                "quantidade": 7,
                                "quantidade_registrada": 7,
                                "valor_unitario": 85.0,
                                "marca_nome": "SUMAY",
                                "status": "disponivel",
                                "imagem_url": "/images/produtos/160422_900052025_57.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                }
];
            }
        },
        Produto: {
            list: async (order = '-created_date', limit = 200) => {
                return [
                {
                                "id": "prod-1",
                                "marca": "SHURE",
                                "modelo": "Sistema sem fio duplo Shure SLxd24d/SM58",
                                "preco": 14100.0,
                                "quantidade": 5,
                                "categoria": "Catálogo",
                                "descricao": "SHURE Sistema sem fio duplo Shure SLxd24d/SM58 - Edital 900142025",
                                "imagem": "/images/produtos/shure-sistema.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-2",
                                "marca": "SHURE",
                                "modelo": "Sistema sem fio duplo Shure SLxd24d/SM58",
                                "preco": 14100.0,
                                "quantidade": 1,
                                "categoria": "Catálogo",
                                "descricao": "SHURE Sistema sem fio duplo Shure SLxd24d/SM58 - Edital 900142025",
                                "imagem": "/images/produtos/930972_900142025_102_1.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-3",
                                "marca": "SUMAY",
                                "modelo": "SLIM BOX 60W",
                                "preco": 190.46,
                                "quantidade": 2,
                                "categoria": "Catálogo",
                                "descricao": "SUMAY SLIM BOX 60W - Edital 900572025",
                                "imagem": "/images/produtos/989983_900572025_6.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-4",
                                "marca": "SUMAY",
                                "modelo": "STONE 12 550W",
                                "preco": 835.0,
                                "quantidade": 8,
                                "categoria": "Catálogo",
                                "descricao": "SUMAY STONE 12 550W - Edital 901292025",
                                "imagem": "/images/produtos/987427_901292025_3.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-5",
                                "marca": "Soundvoice",
                                "modelo": "INTERFACE DE ÁUDIO SOUNDVOICE DELPHI-02",
                                "preco": 538.5,
                                "quantidade": 1,
                                "categoria": "Catálogo",
                                "descricao": "Soundvoice INTERFACE DE ÁUDIO SOUNDVOICE DELPHI-02 - Edital 900142025",
                                "imagem": "/images/produtos/928684_900142025_3_1.png",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-6",
                                "marca": "SMART",
                                "modelo": "TRIPÉ PARA CELULAR UNIVERSAL COM REGULAGEM SMART SM-300",
                                "preco": 375.0,
                                "quantidade": 4,
                                "categoria": "Catálogo",
                                "descricao": "SMART TRIPÉ PARA CELULAR UNIVERSAL COM REGULAGEM SMART SM-300 - Edital 900892025",
                                "imagem": "/images/produtos/158720_900892025_53.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-7",
                                "marca": "THOMASTIK PETER INFELD",
                                "modelo": "JOGO DE CORDAS VIOLA 4/4 - ALPHAYUE",
                                "preco": 550.0,
                                "quantidade": 45,
                                "categoria": "Catálogo",
                                "descricao": "THOMASTIK PETER INFELD JOGO DE CORDAS VIOLA 4/4 - ALPHAYUE - Edital 900922025",
                                "imagem": "/images/produtos/120625_900922025_13.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-8",
                                "marca": "VANDOREN",
                                "modelo": "Palheta de clarineta, nº 3,5, tipo v12,",
                                "preco": 348.0,
                                "quantidade": 20,
                                "categoria": "Catálogo",
                                "descricao": "VANDOREN Palheta de clarineta, nº 3,5, tipo v12, - Edital 4642025",
                                "imagem": "/images/produtos/120016_4642025_2.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-9",
                                "marca": "VANDOREN",
                                "modelo": "BOQUILHA BLACK DIAMOND",
                                "preco": 1489.0,
                                "quantidade": 2,
                                "categoria": "Catálogo",
                                "descricao": "VANDOREN BOQUILHA BLACK DIAMOND - Edital 4642025",
                                "imagem": "/images/produtos/120016_4642025_23.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-10",
                                "marca": "LIVERPOOL",
                                "modelo": "MACETA DE BUMBO PELUCIA",
                                "preco": 32.0,
                                "quantidade": 15,
                                "categoria": "Catálogo",
                                "descricao": "LIVERPOOL MACETA DE BUMBO PELUCIA - Edital 4642025",
                                "imagem": "/images/produtos/120016_4642025_19.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-11",
                                "marca": "LIVERPOOL",
                                "modelo": "PAR DE BAQUETAS 7A HCKT",
                                "preco": 99.0,
                                "quantidade": 15,
                                "categoria": "Catálogo",
                                "descricao": "LIVERPOOL PAR DE BAQUETAS 7A HCKT - Edital 4642025",
                                "imagem": "/images/produtos/120016_4642025_17.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-12",
                                "marca": "SATY",
                                "modelo": "Pedestal para Microfone Saty SMG-10",
                                "preco": 109.0,
                                "quantidade": 5,
                                "categoria": "Catálogo",
                                "descricao": "SATY Pedestal para Microfone Saty SMG-10 - Edital 903012025",
                                "imagem": "/images/produtos/154039_903012025_38.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-13",
                                "marca": "LUEN",
                                "modelo": "CAIXA DE GUERRA 15X14",
                                "preco": 223.0,
                                "quantidade": 12,
                                "categoria": "Catálogo",
                                "descricao": "LUEN CAIXA DE GUERRA 15X14 - Edital 900102024",
                                "imagem": "/images/produtos/160402_900102024_55.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-14",
                                "marca": "LUEN",
                                "modelo": "BOMBO 30X22 Alumisteel Chapa preto 8 Leitosa",
                                "preco": 481.0,
                                "quantidade": 12,
                                "categoria": "Catálogo",
                                "descricao": "LUEN BOMBO 30X22 Alumisteel Chapa preto 8 Leitosa - Edital 900102024",
                                "imagem": "/images/produtos/160402_900102024_56.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-15",
                                "marca": "SUMAY",
                                "modelo": "LIGHT BOX 800W",
                                "preco": 803.85,
                                "quantidade": 2,
                                "categoria": "Catálogo",
                                "descricao": "SUMAY LIGHT BOX 800W - Edital 900282025",
                                "imagem": "/images/produtos/985825_900282025_19.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-16",
                                "marca": "LUEN",
                                "modelo": "PELE LEITOSA 22",
                                "preco": 250.0,
                                "quantidade": 50,
                                "categoria": "Catálogo",
                                "descricao": "LUEN PELE LEITOSA 22 - Edital 900162025",
                                "imagem": "/images/produtos/731050_900162025_10.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-17",
                                "marca": "CASE",
                                "modelo": "CASE",
                                "preco": 399.0,
                                "quantidade": 5,
                                "categoria": "Catálogo",
                                "descricao": "CASE CASE - Edital 900162025",
                                "imagem": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-18",
                                "marca": "REMO",
                                "modelo": "PELE POROSA14\"",
                                "preco": 250.0,
                                "quantidade": 30,
                                "categoria": "Catálogo",
                                "descricao": "REMO PELE POROSA14\" - Edital 900162025",
                                "imagem": "/images/produtos/731050_900162025_15.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-19",
                                "marca": "LUEN",
                                "modelo": "BAQUETA REPIQUE SIMPLES PAR",
                                "preco": 280.0,
                                "quantidade": 30,
                                "categoria": "Catálogo",
                                "descricao": "LUEN BAQUETA REPIQUE SIMPLES PAR - Edital 900162025",
                                "imagem": "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-20",
                                "marca": "LUEN",
                                "modelo": "BAQUETA VANGUARDA PONTA OLIVIA 409MM PAR",
                                "preco": 24.48,
                                "quantidade": 30,
                                "categoria": "Catálogo",
                                "descricao": "LUEN BAQUETA VANGUARDA PONTA OLIVIA 409MM PAR - Edital 900162025",
                                "imagem": "/images/produtos/731050_900162025_18.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-21",
                                "marca": "VANDOREN",
                                "modelo": "Palheta Sax Tenor nº3 caixa com 5 un",
                                "preco": 290.54,
                                "quantidade": 80,
                                "categoria": "Catálogo",
                                "descricao": "VANDOREN Palheta Sax Tenor nº3 caixa com 5 un - Edital 900162025",
                                "imagem": "/images/produtos/731050_900162025_22.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-22",
                                "marca": "Yamaha",
                                "modelo": "Óleo Lubrificante Yamaha Valve Oil - LIGHT 60ml",
                                "preco": 135.03,
                                "quantidade": 70,
                                "categoria": "Catálogo",
                                "descricao": "Yamaha Óleo Lubrificante Yamaha Valve Oil - LIGHT 60ml - Edital 900162025",
                                "imagem": "/images/produtos/731050_900162025_29.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-23",
                                "marca": "LUEN",
                                "modelo": "Pele 16\"",
                                "preco": 350.0,
                                "quantidade": 100,
                                "categoria": "Catálogo",
                                "descricao": "LUEN Pele 16\" - Edital 900162025",
                                "imagem": "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-24",
                                "marca": "LUEN",
                                "modelo": "Pele 16\"",
                                "preco": 400.0,
                                "quantidade": 60,
                                "categoria": "Catálogo",
                                "descricao": "LUEN Pele 16\" - Edital 900162025",
                                "imagem": "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-25",
                                "marca": "SATY",
                                "modelo": "MODELO - SCT 04 Suporte tripé caixa som com ajustes altura",
                                "preco": 133.03,
                                "quantidade": 4,
                                "categoria": "Catálogo",
                                "descricao": "SATY MODELO - SCT 04 Suporte tripé caixa som com ajustes altura - Edital 900082025",
                                "imagem": "/images/produtos/160237_900082025_14.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-26",
                                "marca": "MICHAEL",
                                "modelo": "VIOLÃO ELÉTRICO FOLK VMF400 VMF400",
                                "preco": 1401.0,
                                "quantidade": 3,
                                "categoria": "Catálogo",
                                "descricao": "MICHAEL VIOLÃO ELÉTRICO FOLK VMF400 VMF400 - Edital 900542025",
                                "imagem": "/images/produtos/988157_900542025_3.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-27",
                                "marca": "MICHAEL",
                                "modelo": "VIOLÃO ELÉTRICO CLÁSSICO SEMIFLAT VMS314",
                                "preco": 864.0,
                                "quantidade": 3,
                                "categoria": "Catálogo",
                                "descricao": "MICHAEL VIOLÃO ELÉTRICO CLÁSSICO SEMIFLAT VMS314 - Edital 900542025",
                                "imagem": "/images/produtos/988157_900542025_4.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-28",
                                "marca": "VANRAL",
                                "modelo": "PELE CLEAR DHC 14\"",
                                "preco": 40.0,
                                "quantidade": 20,
                                "categoria": "Catálogo",
                                "descricao": "VANRAL PELE CLEAR DHC 14\" - Edital 900542025",
                                "imagem": "/images/produtos/988881_900542025_1.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-29",
                                "marca": "LIVERPOOL",
                                "modelo": "MAÇANETA MC 48",
                                "preco": 17.65,
                                "quantidade": 7,
                                "categoria": "Catálogo",
                                "descricao": "LIVERPOOL MAÇANETA MC 48 - Edital 900542025",
                                "imagem": "/images/produtos/988881_900542025_5.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-30",
                                "marca": "Nucleo Musical",
                                "modelo": "MICROFONE CSMS 58-BK",
                                "preco": 91.64,
                                "quantidade": 10,
                                "categoria": "Catálogo",
                                "descricao": "Nucleo Musical MICROFONE CSMS 58-BK - Edital 900402025",
                                "imagem": "/images/produtos/984165_900402025_37.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-31",
                                "marca": "Nucleo Musical",
                                "modelo": "Microfone CW 70-BK",
                                "preco": 250.56,
                                "quantidade": 2,
                                "categoria": "Catálogo",
                                "descricao": "Nucleo Musical Microfone CW 70-BK - Edital 900402025",
                                "imagem": "/images/produtos/984165_900402025_38.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-32",
                                "marca": "YAMAHA",
                                "modelo": " Violão Acustico NTX1",
                                "preco": 3012.99,
                                "quantidade": 54,
                                "categoria": "Catálogo",
                                "descricao": "YAMAHA  Violão Acustico NTX1 - Edital 901072025",
                                "imagem": "/images/produtos/158132_901072025_5.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-33",
                                "marca": "AVS",
                                "modelo": "BAG VIOLÃO",
                                "preco": 107.0,
                                "quantidade": 54,
                                "categoria": "Catálogo",
                                "descricao": "AVS BAG VIOLÃO - Edital 901072025",
                                "imagem": "/images/produtos/158132_901072025_6.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-34",
                                "marca": "LUEN",
                                "modelo": "Kit de fanfarra alum. 28 instr",
                                "preco": 14100.0,
                                "quantidade": 6,
                                "categoria": "Catálogo",
                                "descricao": "LUEN Kit de fanfarra alum. 28 instr - Edital 901072025",
                                "imagem": "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&q=80&w=800",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-35",
                                "marca": "BOYA",
                                "modelo": "Sistema de Microfone Lapela Boya By-v20 de Lapela",
                                "preco": 446.25,
                                "quantidade": 3,
                                "categoria": "Catálogo",
                                "descricao": "BOYA Sistema de Microfone Lapela Boya By-v20 de Lapela - Edital 900312025",
                                "imagem": "/images/produtos/987833_900312025_99.jpg",
                                "created_date": "2026-03-05T00:00:00.000Z"
                },
                {
                                "id": "prod-36",
                                "marca": "SUMAY",
                                "modelo": "CAIXA DE SOM COMPUTADOR SM-CSPC1310CAIXASOM2.0",
                                "preco": 85.0,
                                "quantidade": 7,
                                "categoria": "Catálogo",
                                "descricao": "SUMAY CAIXA DE SOM COMPUTADOR SM-CSPC1310CAIXASOM2.0 - Edital 900052025",
                                "imagem": "/images/produtos/160422_900052025_57.webp",
                                "created_date": "2026-03-05T00:00:00.000Z"
                }
];
            }
        },
        Marca: {
            list: async () => {
                return [
                    { id: "m1", nome: "SHURE", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Shure_logo.svg/1024px-Shure_logo.svg.png" },
                    { id: "m2", nome: "SUMAY", logo: "/images/marcas/sumay.png" },
                    { id: "m3", nome: "PEARL", logo: "/images/marcas/pearl.png" },
                    { id: "m4", nome: "VANDOREN", logo: "/images/marcas/vandoren.png" },
                    { id: "m5", nome: "RMV", logo: "/images/marcas/rmv.png" },
                    { id: "m6", nome: "YAMAHA", logo: "/images/marcas/yamaha.png" },
                    { id: "m7", nome: "TAMA", logo: "/images/marcas/tama.png" },
                    { id: "m8", nome: "D'ADDARIO", logo: "/images/marcas/daddario.png" },
                    { id: "m9", nome: "EVANS", logo: "/images/marcas/evans.png" },
                    { id: "m10", nome: "MICHAEL", logo: "https://michael.com.br/site/img/Michael-Logo.png" },
                    { id: "m11", nome: "SATY", logo: "https://saty.com.br/wp-content/themes/saty/img/logo.png" },
                    { id: "m12", nome: "LUEN", logo: "https://luen.com.br/wp-content/uploads/2021/05/logo-luen.png" }
                ];
            }
        }
    }
};
